# Kalman node

# which IMU driver are we using 1 is the heavy and 2 is heavy MKII
# the provided data file is version 1
imu_version: 1
# [x y z roll pitch yaw]
imu_pose: [0, 0, 0, deg(-90), 0, 0]  

# should we use the FOG? Do not set to true if there is no FOG sensor. 
use_gyro: False

#state vector = (x,y,z,roll, pitch, yaw, x_dot,y_dot,z_dot,roll_dot,pitch_dot,yaw_dot)
state_vector: [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0]]
cov_matrix: [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]


sigma_x: 0.0001
sigma_y: 0.01
sigma_z: 0.01
sigma_roll: 0.1
sigma_pitch: 0.0001
sigma_yaw: 0.1
sigma_xd: 0.00015 #settled
sigma_yd: 0.00009 #settled
sigma_zd: 0.1
sigma_rolld: 0.001
sigma_pitchd: 0.01
sigma_yawd: 0.01

Q: [[0.1, 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0.1, 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0.1, 0., 0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0.1, 0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0.1, 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0.1, 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0.1, 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0.1, 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0., 0.1, 0., 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0., 0.,0.1, 0., 0.],
[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,0.1, 0.],
[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,0.1]]

R_dvl: [[0.0001,0.,0.], 
[0.,0.0001,0.,],
[0.,0.,0.001]]  #settled
dt_dvl: 0.2 # 5Hz
H_dvl: [[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,],
[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,],
[0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,]]

R_imu: [[0.01,0.,0.],
[0.,0.01,0.,],
[0.,0.,0.01]]
dt_imu: 0.005 # 200Hz
H_imu: [[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]]

H_gyro: [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]
dt_dvl: 0.004 # 250Hz
R_gyro: [[0.01,0.,0.],
[0.,0.01,0.,],
[0.,0.,0.01]]


